In [1]:
import numpy as np

MAX_RATING = 10
USERS = 5
ITEMS = 6
NUM_RATINGS = 10

In [2]:
M = np.zeros(shape=(USERS, ITEMS), dtype=int)

for n in range(NUM_RATINGS):
    user = np.random.randint(USERS)
    item = np.random.randint(ITEMS)
    rating = np.random.randint(1, MAX_RATING + 1)
    M[user, item] = rating

print(M)

[[10  0  0  6  3  0]
 [ 0  0  0  0  0  0]
 [ 8  0  4  0  8  0]
 [ 0  0  0  3  2  0]
 [ 0  0  0  0  0  0]]


In [3]:
from numpy import linalg
np.set_printoptions(precision=2, suppress=True)

U, Sigma_, V = linalg.svd(M)

In [4]:
print(U)

[[ 0.71 -0.68 -0.2  -0.    0.  ]
 [-0.   -0.   -0.    1.    0.  ]
 [ 0.7   0.71  0.04  0.    0.  ]
 [ 0.12 -0.17  0.98  0.    0.  ]
 [ 0.    0.    0.    0.    1.  ]]


In [5]:
print(V)

[[ 0.8   0.    0.18  0.29  0.5   0.  ]
 [-0.17  0.    0.44 -0.71  0.52  0.  ]
 [-0.58 -0.    0.05  0.58  0.57  0.  ]
 [ 0.03 -0.49 -0.77 -0.23  0.35  0.  ]
 [-0.02 -0.87  0.43  0.13 -0.19  0.  ]
 [ 0.    0.    0.    0.    0.    1.  ]]


In [6]:
print(Sigma_)

[15.87  6.44  2.95  0.    0.  ]


In [7]:
Sigma = np.zeros((USERS, ITEMS))
for i, s in enumerate(Sigma_):
    Sigma[i,i] = s

In [8]:
print(Sigma)

[[15.87  0.    0.    0.    0.    0.  ]
 [ 0.    6.44  0.    0.    0.    0.  ]
 [ 0.    0.    2.95  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]]


In [9]:
M_hat_0 = U @ Sigma @ V

In [10]:
print(M_hat_0)

[[10.  0.  0.  6.  3.  0.]
 [-0. -0. -0.  0. -0.  0.]
 [ 8. -0.  4.  0.  8.  0.]
 [ 0. -0.  0.  3.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [11]:
linalg.norm(M_hat_0 - M)

6.6539376261076315e-15